3proxy:
  build: .
  container_name: 3proxy
  restart: always
  ports:
    - 8080:8080
    - 3128:3128
  volumes:
    - ./3proxy.cfg:/etc/3proxy/3proxy.cfg:ro
    - ./3proxy.log:/var/log:rw
    - ./.proxyauth:/etc/3proxy/.proxyauth
  privileged: True
